Repository spdx/ntia-conformance-checker, pull requests merged in 2023-01, with the labels that each got.

#31 Use Upstream spdx-tools and Make Necessary Changes
  .github/workflows/python-app.yml
  .gitignore
  Pipfile
  Pipfile.lock
  ntia_conformance_checker/cli_tools/check_anything.py
  setup.py
  tests/data/missing_author_name/SPDXJsonExample.json
  tests/data/missing_author_name/SPDXXmlExample.xml
  tests/data/missing_author_name/SPDXYamlExample.yaml
  tests/data/missing_component_version/SPDXJsonExample.json
  tests/data/missing_component_version/SPDXXmlExample.xml
  tests/data/missing_component_version/SPDXYamlExample.yaml
  tests/data/missing_dependency_relationships/SPDXJsonExample.json
  tests/data/missing_dependency_relationships/SPDXSimpleTag.tag
  tests/data/missing_dependency_relationships/SPDXTagExample.tag
  tests/data/missing_dependency_relationships/SPDXXmlExample.xml
  tests/data/missing_dependency_relationships/SPDXYamlExample.yaml
  tests/data/missing_supplier_name/SPDXJsonExample.json
  tests/data/missing_supplier_name/SPDXXmlExample.xml
  tests/data/missing_supplier_name/SPDXYamlExample.yaml
  tests/data/missing_timestamp/SPDXXmlExample.xml
  tests/data/missing_unique_identifiers/SPDXJsonExample.json
  tests/data/missing_unique_identifiers/SPDXTagExample.tag
  tests/data/missing_unique_identifiers/SPDXXmlExample.xml
  tests/data/missing_unique_identifiers/SPDXYamlExample.yaml
  tests/data/no_elements_missing/SPDXJsonExample.json
  tests/data/no_elements_missing/SPDXXmlExample.xml
  tests/data/no_elements_missing/SPDXYamlExample.yaml
  tests/test_checker.py
Labels: bug, enhancement

#34 Make Organization a Valid SBOM Author Entity
  ntia_conformance_checker/cli_tools/check_anything.py
  tests/data/missing_author_name/SPDXRdfExample.rdf
  tests/data/missing_author_name/SPDXTagExample.tag
Labels: bug

#35 Update usage instruction
  README.md
Labels: documentation

#36 Add testing coverage to PRs
  .github/workflows/python-app.yml
Labels: enhancement

#41 Rearchitect to Object-Oriented Design
  README.md
  ntia_conformance_checker/cli_tools/__init__.py
  ntia_conformance_checker/cli_tools/check_anything.py
  ntia_conformance_checker/cli_tools/output.py
  ntia_conformance_checker/main.py
  ntia_conformance_checker/sbom_checker.py
  tests/test_checker.py
Labels: enhancement

#44 Add build passing badge
  .github/workflows/build.yml
  README.md
Labels: documentation, enhancement

#45 Add functionality and tests for retrieving number of components
  ntia_conformance_checker/sbom_checker.py
  tests/test_checker.py
Labels: enhancement

#47 Replace setup.py with pyproject.toml
  pyproject.toml
  setup.py
Labels: enhancement

#50 Fix README mistake
  README.md
Labels: bug, documentation

#56 Fix author check
  README.md
  ntia_conformance_checker/sbom_checker.py
  tests/data/SPDXSBOMExampleTests/photon.spdx.tag
  tests/data/missing_author_name/SPDXJsonExample.json
  tests/data/missing_author_name/SPDXRdfExample.rdf
  tests/data/missing_author_name/SPDXTagExample.tag
  tests/data/missing_author_name/SPDXXmlExample.xml
  tests/data/missing_author_name/SPDXYamlExample.yaml
  tests/test_checker.py
Labels: bug

#55 Add graceful exit when file does not exist
  ntia_conformance_checker/sbom_checker.py
Labels: enhancement

#60 Add FAQ
  FAQ.md
  README.md
Labels: documentation, enhancement

#61 Setup for release to PyPI
  .gitignore
  CONTRIBUTING.md
  README.md
  ntia_conformance_checker/main.py
  ntia_conformance_checker/sbom_checker.py
  pyproject.toml
  setup.py
Labels: enhancement

#58 Add quiet mode
  ntia_conformance_checker/main.py
Labels: enhancement

#63 Add proper contact email to pyproject.toml
  pyproject.toml
Labels: documentation

#67 Use property, not method, in main.py
  ntia_conformance_checker/main.py
Labels: enhancement
