Repository spdx/ntia-conformance-checker, pull requests merged in 2023-09, with the labels that each got.

#151 Make --file argument optional
  ntia_conformance_checker/main.py
Labels: bug

#152 Create release.md
  release.md
Labels: documentation

#154 Fix file argument
  ntia_conformance_checker/main.py
Labels: bug

#156 support for -v shorthand for --verbose
  README.md
  ntia_conformance_checker/main.py
Labels: bug, documentation
