Repository spdx/ntia-conformance-checker, pull requests merged in 2024-06, with the labels that each got.

#187 Add Docker Version to Installation Instructions
  README.md
Labels: documentation

#189 Find the DESCRIBES relationship by looking through attached packages
  ntia_conformance_checker/sbom_checker.py
Labels: bug, breaking-change

#190 Add scorecard GitHub Action YAML
  .github/workflows/scorecard.yml
Labels: security

#191 Add Scorecard Badge to README
  README.md
Labels: documentation
