Repository spdx/ntia-conformance-checker, pull requests merged in 2025-03, with the labels that each got.

#259 Ignore a false positive CVE finding
  tests/data/SPDXSBOMExampleTests/osv-scanner.toml
Labels: security

#260 Update Pylint Score to 10
  README.md
Labels: documentation

#261 Bump release version
  pyproject.toml
Labels: release
