Repository spdx/ntia-conformance-checker, pull requests merged in 2025-08, with the labels that each got.

#280 Delete malcontent malware analysis workflow
  .github/workflows/malcontent.yaml
Labels: security

#282 Separate SPDX 2-specific code to make room for SPDX 3 code
  ntia_conformance_checker/base_checker.py
  ntia_conformance_checker/fsct_checker.py
  ntia_conformance_checker/main.py
  ntia_conformance_checker/ntia_checker.py
  ntia_conformance_checker/sbom_checker.py
Labels: enhancement

#283 Test package on multiple Python versions
  .github/workflows/build.yml
  .github/workflows/pylint.yml
  .github/workflows/typecheck.yml
  Pipfile
  Pipfile.lock
  README.md
  pyproject.toml
  tests/test_checker.py
  tests/test_main.py
Labels: github_actions, tests

#284 Add SPDX 3 JSON parse function
  README.md
  ntia_conformance_checker/base_checker.py
  ntia_conformance_checker/cli_utils.py
  ntia_conformance_checker/fsct_checker.py
  ntia_conformance_checker/main.py
  ntia_conformance_checker/ntia_checker.py
  ntia_conformance_checker/sbom_checker.py
  pyproject.toml
  tests/data/spdx3/README.md
  tests/data/spdx3/has_no_sbom.json
  tests/data/spdx3/has_no_software_package.json
  tests/data/spdx3/has_sbom.json
  tests/data/spdx3/software-example03.json
  tests/test_checker.py
Labels: enhancement
